In [54]:
import pandas as pd

In [55]:
import numpy as np

In [56]:
import matplotlib.pyplot as plt

In [57]:
import seaborn as sns

In [58]:
df = pd.read_csv('../data/sales_data.csv')

In [59]:
df.head()

,sale_id,date,vehicle_type,state,industry,unit_price,units_sold,revenue
0,1,2022-01-01,Construction Equipment,WA,Mining,437580.0,2,875160
1,2,2022-01-02,Bus,WA,Agriculture,317208.0,1,317208
2,3,2022-01-03,Light Commercial,WA,Mining,136403.0,1,136403
3,4,2022-01-04,Bus,WA,Mining,181170.0,1,181170
4,5,2022-01-05,Bus,SA,Logistics,361312.0,1,361312

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_id       1000 non-null   int64
 1   date          1000 non-null   object
 2   vehicle_type  1000 non-null   object
 3   state         1000 non-null   object
 4   industry      970 non-null    object
 5   unit_price    980 non-null    float64
 6   units_sold    1000 non-null   int64
 7   revenue       1000 non-null   int64
dtypes: float64(1), int64(3), object(4)
memory usage: 62.6+ KB

In [61]:
df['date']= pd.to_datetime(df['date'])

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_id       1000 non-null   int64
 1   date          1000 non-null   datetime64[ns]
 2   vehicle_type  1000 non-null   object
 3   state         1000 non-null   object
 4   industry      970 non-null    object
 5   unit_price    980 non-null    float64
 6   units_sold    1000 non-null   int64
 7   revenue       1000 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 62.6+ KB

In [63]:
df.isnull().sum()

sale_id          0
date             0
vehicle_type     0
state            0
industry        30
unit_price      20
units_sold       0
revenue          0
dtype: int64

In [64]:
df = pd.read_csv('../data/sales_data.csv')
df['date'] = pd.to_datetime(df['date'])
df.isnull().sum()

sale_id          0
date             0
vehicle_type     0
state            0
industry        30
unit_price      20
units_sold       0
revenue          0
dtype: int64

In [65]:
df['industry'] = df['industry'].fillna('Unknown')
df['unit_price'] = df['unit_price'].fillna(df['unit_price'].mean())

In [66]:
df.isnull().sum()

sale_id         0
date            0
vehicle_type    0
state           0
industry        0
unit_price      0
units_sold      0
revenue         0
dtype: int64

In [67]:
total_revenue = df['revenue'].sum()

total_units = df['units_sold'].sum()

avg_price = df['unit_price'].mean()

total_sales = len(df)

In [68]:
df['year_month'] = df['date'].dt.to_period('M')

In [69]:
monthly_sales = df.groupby('year_month')['revenue'].sum().reset_index(    name='total_revenue'    )

In [70]:
monthly_sales.head(10)

  year_month  total_revenue
0    2022-01       21702882
1    2022-02       22343087
2    2022-03       25141816
3    2022-04       17646783
4    2022-05       17751973
5    2022-06       27932501
6    2022-07       26519643
7    2022-08       26478123
8    2022-09       20756499
9    2022-10       22693951